import React, { useState, useEffect } from 'react';
import { Container, Row, Col, Spinner } from 'reactstrap';

export const Resurrect = () => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => setLoading(false), 3500);
    return () => clearTimeout(timer);
  }, []);

  if (loading) {
    return (
      <Container className="text-center mt-5 pt-5">
        <div style={{ height: '300px', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}>
          <Spinner color="success" style={{ width: '8rem', height: '8rem', borderWidth: '0.5rem' }} className="mb-4" />
          <h1 className="text-success mt-4">Resurrecting Protocol...</h1>
          <p className="text-muted lead">Re-writing vulnerable logic and clearing misinformation.</p>
        </div>
      </Container>
    );
  }

  return (
    <Container fluid className="mt-4 px-5">
      <div className="text-center mb-5">
        <h1 className="display-4 font-weight-bold">Code Resurrection</h1>
        <p className="lead text-muted">Vulnerabilities patched. Comments sanitized by LLM.</p>
      </div>

      <Row>
        <Col md="6">
          <div className="shadow-lg" style={{ borderRadius: '15px', overflow: 'hidden' }}>
            <div className="bg-danger text-white p-3 font-weight-bold">ORIGINAL VULNERABLE CONTRACT</div>
            <div
              className="bg-dark text-white p-4"
              style={{ minHeight: '800px', fontFamily: '"Courier New", Courier, monospace', fontSize: '14px' }}
            >
              <pre style={{ color: '#ffb3b3' }}>{`
// @notice This contract is abandoned. 
// @dev DO NOT USE THIS. It has no reentrancy protection.
contract LegacyVault {
    mapping(address => uint) public balances;

    function deposit() public payable {
        balances[msg.sender] += msg.value;
    }

    function withdraw(uint _amount) public {
        require(balances[msg.sender] >= _amount);
        
        // VULNERABILITY: Low level call before state update
        (bool success, ) = msg.sender.call{value: _amount}("");
        if(success) {
            balances[msg.sender] -= _amount;
        }
    }
}
              `}</pre>
            </div>
          </div>
        </Col>

        <Col md="6">
          <div className="shadow-lg" style={{ borderRadius: '15px', overflow: 'hidden' }}>
            <div className="bg-success text-white p-3 font-weight-bold">REVIVED SECURE CONTRACT</div>
            <div
              className="bg-dark text-white p-4"
              style={{ minHeight: '800px', fontFamily: '"Courier New", Courier, monospace', fontSize: '14px' }}
            >
              <pre style={{ color: '#b3ffb3' }}>{`
// @notice Secure version generated by Revival.
// @dev Reentrancy Guard implemented via Checks-Effects-Interactions.
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";

contract RevivedVault is ReentrancyGuard {
    mapping(address => uint) public balances;

    function deposit() public payable {
        balances[msg.sender] += msg.value;
    }

    function withdraw(uint _amount) public nonReentrant {
        require(balances[msg.sender] >= _amount, "Insufficient balance");
        
        // FIXED: Balance deducted before external call
        balances[msg.sender] -= _amount;
        
        (bool success, ) = msg.sender.call{value: _amount}("");
        require(success, "Transfer failed");
    }
}
              `}</pre>
            </div>
          </div>
        </Col>
      </Row>
    </Container>
  );
};

export default Resurrect;
