package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SmartContractAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmartContractAllPropertiesEquals(SmartContract expected, SmartContract actual) {
        assertSmartContractAutoGeneratedPropertiesEquals(expected, actual);
        assertSmartContractAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmartContractAllUpdatablePropertiesEquals(SmartContract expected, SmartContract actual) {
        assertSmartContractUpdatableFieldsEquals(expected, actual);
        assertSmartContractUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmartContractAutoGeneratedPropertiesEquals(SmartContract expected, SmartContract actual) {
        assertThat(actual)
            .as("Verify SmartContract auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmartContractUpdatableFieldsEquals(SmartContract expected, SmartContract actual) {
        assertThat(actual)
            .as("Verify SmartContract relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getGithubUrl()).as("check githubUrl").isEqualTo(expected.getGithubUrl()))
            .satisfies(a -> assertThat(a.getOriginalCode()).as("check originalCode").isEqualTo(expected.getOriginalCode()))
            .satisfies(a -> assertThat(a.getResurrectedCode()).as("check resurrectedCode").isEqualTo(expected.getResurrectedCode()))
            .satisfies(a -> assertThat(a.getIsValidated()).as("check isValidated").isEqualTo(expected.getIsValidated()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmartContractUpdatableRelationshipsEquals(SmartContract expected, SmartContract actual) {
        // empty method
    }
}
